mex_category_db.mexa64: mex_category_db.o \
  ../../bin/concurrent/threads/child_thread.o \
  ../../bin/concurrent/threads/runnable.o \
  ../../bin/concurrent/threads/synchronization/synchronizables/synchronizable.o \
  ../../bin/concurrent/threads/synchronization/synchronizables/unsynchronized.o \
  ../../bin/concurrent/threads/thread.o \
  ../../bin/io/serialization/serial_input_stream.o \
  ../../bin/io/serialization/serial_output_stream.o \
  ../../bin/lang/array.o \
  ../../bin/lang/exceptions/ex_bad_cast.o \
  ../../bin/lang/exceptions/ex_index_out_of_bounds.o \
  ../../bin/lang/exceptions/ex_invalid_argument.o \
  ../../bin/lang/exceptions/ex_not_found.o \
  ../../bin/lang/exceptions/ex_null_pointer_dereference.o \
  ../../bin/lang/exceptions/exception.o \
  ../../bin/lang/exceptions/throwable.o \
  ../../bin/math/math.o \
  ../../bin/math/matrices/exceptions/ex_matrix_dimension_mismatch.o \
  ../../bin/math/matrices/exceptions/ex_matrix_singular.o \
  ../../bin/math/matrices/matrix.o \
  ../../bin/math/random/generators/rand_gen_uniform.o \
  ../../bin/math/random/sources/mersenne_twister_64.o \
  ../../bin/math/random/sources/rand_source.o \
  ../../bin/math/random/sources/rand_source_64.o \
  ../../bin/math/random/sources/rand_source_default.o \
  ../../bin/math/random/sources/system_entropy.o \
  ../../bin/vision/features/feature.o \
  ../../bin/vision/features/feature_descriptor.o \
  ../../bin/vision/features/feature_id.o \
  ../../bin/vision/features/geometric_blur.o \
  ../../bin/vision/features/parameters/geometric_blur_params.o \
  ../../bin/vision/recognition/classifiers/abstract/classifier.o \
  ../../bin/vision/recognition/classifiers/bigram_classifier.o \
  ../../bin/vision/recognition/classifiers/unigram_classifier.o \
  ../../bin/vision/recognition/databases/category_db.o \
  ../../bin/vision/recognition/models/category.o \
  ../../bin/vision/recognition/models/exemplar.o \
  ../../bin/vision/recognition/models/ids/category_id.o \
  ../../bin/vision/recognition/models/ids/exemplar_id.o \
  ../../bin/vision/recognition/models/ids/feature_id.o